server:
  port: 80
  context-path: /JD
  

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/jd?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
   jpa:
     hibernate.ddl-auto: update
     show-sql: true





